osx_image: xcode7.3

sudo: false
dist: trusty

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
    - node_modules
    - app/node_modules
    - "$HOME/.electron"
    - "$HOME/.cache"

install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.2.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.2.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -L https://github.com/yarnpkg/yarn/releases/download/v1.0.1/yarn-v1.0.1.tar.gz | tar xvz && mv yarn-v1.0.1 $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn

script:
  - yarn dist

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
