platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'

install:
  - ps: Install-Product node 8 x64
  - npm install -g gulp-cli
  - yarn

build_script:
  - gulp
#  - ps: yarn test; if ($?) { yarn dist }
  - yarn creds
  - node bin/contributors.js
  - yarn dist

test: off
